<a href="https://colab.research.google.com/github/parkjy0629/tensorflow_study/blob/main/tensorflow_python/dl3_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1. 과거 데이터 준비
file_path = 'https://raw.githubusercontent.com/parkjy0629/tensorflow_study/main/study_csv/iris.csv'
iris = pd.read_csv(file_path)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 2. 원핫인코딩
inc = pd.get_dummies(iris)
inc.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2       True          False         False
1   4.9  3.0    1.4   0.2       True          False         False
2   4.7  3.2    1.3   0.2       True          False         False
3   4.6  3.1    1.5   0.2       True          False         False
4   5.0  3.6    1.4   0.2       True          False         False

In [5]:
print(inc.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [7]:
# 3. 독립변수, 종속변수 분리
i_var = inc[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
d_var = inc[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(i_var.shape, d_var.shape)

(150, 4) (150, 3)


In [16]:
# 4. 모델 구조 만들기
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

In [20]:
# 5. 모델 학습
model.fit(i_var, d_var, epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8586 - loss: 0.5729 
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8539 - loss: 0.5779 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8711 - loss: 0.5806 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8839 - loss: 0.5911 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8814 - loss: 0.5661 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8827 - loss: 0.5652 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8848 - loss: 0.5631 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8551 - loss: 0.5478 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8902 - loss: 0.5836 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8763 - loss: 0.5783 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8678 - loss: 0.5671 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8756 - los

In [21]:
# 모델 이용
model.predict(i_var[0:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[0.90406746, 0.084428  , 0.01150451],
       [0.8745509 , 0.1097636 , 0.01568557],
       [0.8883356 , 0.09694339, 0.01472102],
       [0.8602938 , 0.11907764, 0.0206285 ],
       [0.9059503 , 0.0822228 , 0.01182698]], dtype=float32)

In [22]:
print(d_var[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0       True          False         False
1       True          False         False
2       True          False         False
3       True          False         False
4       True          False         False


In [23]:
# 마지막 5번째 확인
model.predict(i_var[-5:])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[0.00699539, 0.3584973 , 0.6345073 ],
       [0.01265476, 0.41463986, 0.5727054 ],
       [0.0115023 , 0.38647646, 0.6020212 ],
       [0.0051132 , 0.28192595, 0.71296084],
       [0.01419554, 0.36694083, 0.6188636 ]], dtype=float32)

In [24]:
print(d_var[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145      False          False          True
146      False          False          True
147      False          False          True
148      False          False          True
149      False          False          True


In [25]:
# 학습한 가중치
model.get_weights()

[array([[ 0.5085286 ,  0.29011518, -0.1643478 ],
        [ 0.30545324, -0.1984279 , -0.11178639],
        [-0.8962371 , -0.06876433,  0.4060675 ],
        [-1.0694842 ,  0.48327726,  1.2119384 ]], dtype=float32),
 array([ 0.93490076, -0.02762571, -0.8167666 ], dtype=float32)]